"""Fail-closed release evidence checks. Format validity alone is not approval."""
from __future__ import annotations
import math


def check_release(report, probability_sha256, policy):
    if report.get("status") != "completed":
        raise ValueError("validation incomplete")
    if report.get("protocol") != "spatial-4x4-strided-v1-buffer40-top2":
        raise ValueError("incompatible or missing spatial holdout protocol")
    if report.get("policy") != policy:
        raise ValueError("policy differs from validated policy")
    rows = report.get("folds", [])
    if sorted(r.get("fold", -1) for r in rows) != [0, 1, 2, 3]:
        raise ValueError("all four spatial folds required")
    rows = sorted(rows, key=lambda x: x["fold"])
    for baseline in ("baseline107", "baseline107_discovery"):
        deltas = []
        for row in rows:
            scores = row.get("scores", {})
            c = scores.get("H12", {}).get("dti", float("nan"))
            b = scores.get(baseline, {}).get("dti", float("nan"))
            if not all(isinstance(v, (float, int)) and math.isfinite(v) and 0 <= v <= 1
                       for v in (c, b)):
                raise ValueError("missing or invalid fold scores")
            deltas.append(c-b)
        if sum(deltas[:3])/3 <= 0 or deltas[3] <= 0:
            raise ValueError(f"H12 did not beat {baseline} on development AND confirmation")
    # This binding must be generated by a reproducible final-training recipe,
    # never just a boolean claiming success. Currently no candidate has this attestation.
    binding = report.get("final_prediction", {})
    if binding.get("sha256") != probability_sha256 or not binding.get("training_manifest_sha256"):
        raise ValueError("final predictions are not bound to validated training evidence")
    if not report.get("promotion_allowed", False):
        raise ValueError("release not approved by evidence report")


def verify_training_binding(report, root):
    """Verify evidence file hashes, not merely a boolean / arbitrary hash string.

    Large model weights need not be on Pages; the small final-training manifest
    records their hash and the same feature/input/config identity as validation.
    """
    import json
    from pathlib import Path
    from .raster import sha256_file

    root = Path(root).resolve()
    binding = report.get('final_prediction', {})
    name = binding.get('training_manifest_file', '')
    if not name or Path(name).name != name:
        raise ValueError('training manifest basename missing or unsafe')
    path = root / 'reports' / name
    if not path.is_file() or sha256_file(path) != binding.get('training_manifest_sha256'):
        raise ValueError('training manifest missing or hash mismatch')
    manifest = json.loads(path.read_text())
    expected = {'hypothesis': 'H12', 'probability_sha256': binding.get('sha256'),
                'validation_protocol': report.get('protocol'),
                'validated_inputs': report.get('inputs'), 'config': report.get('config')}
    if not report.get('inputs') or not report.get('config'):
        raise ValueError('validation input/config provenance absent')
    for key, value in expected.items():
        if manifest.get(key) != value:
            raise ValueError(f'training manifest differs from validation: {key}')
    if not manifest.get('model_sha256'):
        raise ValueError('trained model identity absent')
    code = report.get('code', {})
    if not code:
        raise ValueError('validation code hashes absent')
    for relative, digest in code.items():
        p = (root / relative).resolve()
        if not p.is_relative_to(root) or not p.is_file() or sha256_file(p) != digest:
            raise ValueError(f'validation code changed or missing: {relative}')
