"""Fail-closed release evidence checks. Format validity alone is not approval."""
from __future__ import annotations
import math


# Known spatial holdout protocols. v1 (H12-era): scalar dti per arm per fold.
# v2 (session 2): per-policy score dicts; per-arm policy selected on the
# development folds only (preregistered in HYPOTHESES.md).
# v3 (session 3): v2 structure with the 16-policy union (thin family added), an
# explicit `arms` list, and `decision.comparisons` that must ALL pass — including
# the same-run H16 incumbent arm and the external incumbent report when present.
PROTOCOLS = ("spatial-4x4-strided-v1-buffer40-top2",
             "spatial-4x4-strided-v1-buffer40-policy-sweep-v2",
             "spatial-4x4-strided-v1-buffer40-policy-sweep-v3")


def _fold_dti(row, arm, selection):
    """DTI for (fold row, arm) under the arm's selected policy (v2) or
    scalar (v1)."""
    scores = row.get("scores", {}).get(arm)
    if scores is None:
        return float("nan")
    if isinstance(scores, dict) and "dti" not in scores:  # v2: {policy: {...}}
        pol = (selection or {}).get(arm)
        if not pol or pol not in scores:
            return float("nan")
        v = scores[pol].get("dti", float("nan"))
    else:  # v1: {"dti": ...}
        v = scores.get("dti", float("nan"))
    if not (isinstance(v, (float, int)) and math.isfinite(v) and 0 <= v <= 1):
        return float("nan")
    return float(v)


def check_release(report, probability_sha256, policy):
    if report.get("status") != "completed":
        raise ValueError("validation incomplete")
    if report.get("protocol") not in PROTOCOLS:
        raise ValueError("incompatible or missing spatial holdout protocol")
    is_v2 = report.get("protocol") in PROTOCOLS[1:]
    is_v3 = report.get("protocol") == PROTOCOLS[2]
    if is_v2:
        selection = report.get("policy_selection")
        if not selection:
            raise ValueError("v2 report lacks per-arm policy selection")
        # The eligible policy is the candidate arm's selected policy (the
        # primary policy is a reporting default, not the validated choice).
        candidate = report.get("hypothesis") or "H12"
        if selection.get(candidate) != policy:
            raise ValueError("policy differs from the validated selected policy")
    else:
        if report.get("policy") != policy:
            raise ValueError("policy differs from validated policy")
        selection = {}
    rows = report.get("folds", [])
    if sorted(r.get("fold", -1) for r in rows) != [0, 1, 2, 3]:
        raise ValueError("all four spatial folds required")
    rows = sorted(rows, key=lambda x: x["fold"])
    candidate = report.get("hypothesis") or "H12"
    for baseline in ("baseline107", "baseline107_discovery"):
        deltas = []
        for row in rows:
            c = _fold_dti(row, candidate, selection)
            b = _fold_dti(row, baseline, selection)
            if not (math.isfinite(c) and math.isfinite(b)):
                raise ValueError("missing or invalid fold scores")
            deltas.append(c-b)
        if sum(deltas[:3])/3 <= 0 or deltas[3] <= 0:
            raise ValueError(f"{candidate} did not beat {baseline} on development AND confirmation")
    if is_v3:
        # Every recorded comparison (baselines, same-run incumbent arm, external
        # incumbent report) must pass, recomputed here from the fold rows where
        # the arm is present in this report; the external one is trusted from
        # the recorded deltas but must be flagged as passing.
        comparisons = (report.get("decision") or {}).get("comparisons") or {}
        if not comparisons:
            raise ValueError("v3 report lacks decision comparisons")
        for name, comp in comparisons.items():
            if not comp.get("passes"):
                raise ValueError(f"{candidate} did not beat incumbent {name}")
            if name in (report.get("arms") or []) and name != candidate:
                deltas = []
                for row in rows:
                    c = _fold_dti(row, candidate, selection)
                    b = _fold_dti(row, name, selection)
                    if not (math.isfinite(c) and math.isfinite(b)):
                        raise ValueError("missing or invalid fold scores")
                    deltas.append(c - b)
                if sum(deltas[:3]) / 3 <= 0 or deltas[3] <= 0:
                    raise ValueError(f"{candidate} did not beat {name} on development AND confirmation")
            elif name.startswith("incumbent_report:"):
                d = comp.get("delta_by_fold") or []
                if len(d) != 4 or sum(d[:3]) / 3 <= 0 or d[3] <= 0:
                    raise ValueError(f"{candidate} did not beat {name} on development AND confirmation")
        if not (report.get("decision") or {}).get("eligible"):
            raise ValueError("v3 decision not eligible")
    # This binding must be generated by a reproducible final-training recipe,
    # never just a boolean claiming success. Currently no candidate has this attestation.
    binding = report.get("final_prediction", {})
    if binding.get("sha256") != probability_sha256 or not binding.get("training_manifest_sha256"):
        raise ValueError("final predictions are not bound to validated training evidence")
    if not report.get("promotion_allowed", False):
        raise ValueError("release not approved by evidence report")


def verify_training_binding(report, root):
    """Verify evidence file hashes, not merely a boolean / arbitrary hash string.

    Large model weights need not be on Pages; the small final-training manifest
    records their hash and the same feature/input/config identity as validation.
    """
    import json
    from pathlib import Path
    from .raster import sha256_file

    root = Path(root).resolve()
    binding = report.get('final_prediction', {})
    name = binding.get('training_manifest_file', '')
    if not name or Path(name).name != name:
        raise ValueError('training manifest basename missing or unsafe')
    path = root / 'reports' / name
    if not path.is_file() or sha256_file(path) != binding.get('training_manifest_sha256'):
        raise ValueError('training manifest missing or hash mismatch')
    manifest = json.loads(path.read_text())
    expected = {'hypothesis': report.get('hypothesis') or 'H12',
                'probability_sha256': binding.get('sha256'),
                'validation_protocol': report.get('protocol'),
                'validated_inputs': report.get('inputs'), 'config': report.get('config')}
    if not report.get('inputs') or not report.get('config'):
        raise ValueError('validation input/config provenance absent')
    for key, value in expected.items():
        if manifest.get(key) != value:
            raise ValueError(f'training manifest differs from validation: {key}')
    if not manifest.get('model_sha256'):
        raise ValueError('trained model identity absent')
    code = report.get('code', {})
    if not code:
        raise ValueError('validation code hashes absent')
    if manifest.get('code') != code:
        raise ValueError('training manifest code hashes differ from validation')
    for relative, digest in code.items():
        p = (root / relative).resolve()
        if not p.is_relative_to(root):
            raise ValueError(f'validation code path escapes the repository: {relative}')
        if p.is_file() and sha256_file(p) == digest:
            continue
        # The working tree moved on (later sessions edit code); the evidence is
        # still valid if the exact validated file content exists in this
        # repository's git history (the report + manifest pin its sha256).
        if not _sha256_in_git_history(root, relative, digest):
            raise ValueError(f'validation code changed or missing: {relative}')


def _sha256_in_git_history(root, relative, digest, max_commits=400) -> bool:
    """True if some committed version of `relative` hashes to `digest`."""
    import hashlib
    import subprocess
    try:
        log = subprocess.run(['git', '-C', str(root), 'log', '--all', f'-n{max_commits}',
                              '--format=%H', '--', relative],
                             capture_output=True, text=True, check=True, timeout=60).stdout.split()
    except Exception:
        return False
    for commit in log:
        try:
            blob = subprocess.run(['git', '-C', str(root), 'show', f'{commit}:{relative}'],
                                  capture_output=True, check=True, timeout=60).stdout
        except Exception:
            continue
        if hashlib.sha256(blob).hexdigest() == digest:
            return True
    return False
