"""Fail-closed release evidence checks. Format validity alone is not approval."""
from __future__ import annotations
import math


# Known spatial holdout protocols. v1 (H12-era): scalar dti per arm per fold.
# v2 (session 2): per-policy score dicts; per-arm policy selected on the
# development folds only (preregistered in HYPOTHESES.md).
PROTOCOLS = ("spatial-4x4-strided-v1-buffer40-top2",
             "spatial-4x4-strided-v1-buffer40-policy-sweep-v2")


def _fold_dti(row, arm, selection):
    """DTI for (fold row, arm) under the arm's selected policy (v2) or
    scalar (v1)."""
    scores = row.get("scores", {}).get(arm)
    if scores is None:
        return float("nan")
    if isinstance(scores, dict) and "dti" not in scores:  # v2: {policy: {...}}
        pol = (selection or {}).get(arm)
        if not pol or pol not in scores:
            return float("nan")
        v = scores[pol].get("dti", float("nan"))
    else:  # v1: {"dti": ...}
        v = scores.get("dti", float("nan"))
    if not (isinstance(v, (float, int)) and math.isfinite(v) and 0 <= v <= 1):
        return float("nan")
    return float(v)


def check_release(report, probability_sha256, policy):
    if report.get("status") != "completed":
        raise ValueError("validation incomplete")
    if report.get("protocol") not in PROTOCOLS:
        raise ValueError("incompatible or missing spatial holdout protocol")
    is_v2 = report.get("protocol") == PROTOCOLS[1]
    if is_v2:
        selection = report.get("policy_selection")
        if not selection:
            raise ValueError("v2 report lacks per-arm policy selection")
        # The eligible policy is the candidate arm's selected policy (the
        # primary policy is a reporting default, not the validated choice).
        candidate = report.get("hypothesis") or "H12"
        if selection.get(candidate) != policy:
            raise ValueError("policy differs from the validated selected policy")
    else:
        if report.get("policy") != policy:
            raise ValueError("policy differs from validated policy")
        selection = {}
    rows = report.get("folds", [])
    if sorted(r.get("fold", -1) for r in rows) != [0, 1, 2, 3]:
        raise ValueError("all four spatial folds required")
    rows = sorted(rows, key=lambda x: x["fold"])
    candidate = report.get("hypothesis") or "H12"
    for baseline in ("baseline107", "baseline107_discovery"):
        deltas = []
        for row in rows:
            c = _fold_dti(row, candidate, selection)
            b = _fold_dti(row, baseline, selection)
            if not (math.isfinite(c) and math.isfinite(b)):
                raise ValueError("missing or invalid fold scores")
            deltas.append(c-b)
        if sum(deltas[:3])/3 <= 0 or deltas[3] <= 0:
            raise ValueError(f"{candidate} did not beat {baseline} on development AND confirmation")
    # This binding must be generated by a reproducible final-training recipe,
    # never just a boolean claiming success. Currently no candidate has this attestation.
    binding = report.get("final_prediction", {})
    if binding.get("sha256") != probability_sha256 or not binding.get("training_manifest_sha256"):
        raise ValueError("final predictions are not bound to validated training evidence")
    if not report.get("promotion_allowed", False):
        raise ValueError("release not approved by evidence report")


def verify_training_binding(report, root):
    """Verify evidence file hashes, not merely a boolean / arbitrary hash string.

    Large model weights need not be on Pages; the small final-training manifest
    records their hash and the same feature/input/config identity as validation.
    """
    import json
    from pathlib import Path
    from .raster import sha256_file

    root = Path(root).resolve()
    binding = report.get('final_prediction', {})
    name = binding.get('training_manifest_file', '')
    if not name or Path(name).name != name:
        raise ValueError('training manifest basename missing or unsafe')
    path = root / 'reports' / name
    if not path.is_file() or sha256_file(path) != binding.get('training_manifest_sha256'):
        raise ValueError('training manifest missing or hash mismatch')
    manifest = json.loads(path.read_text())
    expected = {'hypothesis': report.get('hypothesis') or 'H12',
                'probability_sha256': binding.get('sha256'),
                'validation_protocol': report.get('protocol'),
                'validated_inputs': report.get('inputs'), 'config': report.get('config')}
    if not report.get('inputs') or not report.get('config'):
        raise ValueError('validation input/config provenance absent')
    for key, value in expected.items():
        if manifest.get(key) != value:
            raise ValueError(f'training manifest differs from validation: {key}')
    if not manifest.get('model_sha256'):
        raise ValueError('trained model identity absent')
    code = report.get('code', {})
    if not code:
        raise ValueError('validation code hashes absent')
    for relative, digest in code.items():
        p = (root / relative).resolve()
        if not p.is_relative_to(root) or not p.is_file() or sha256_file(p) != digest:
            raise ValueError(f'validation code changed or missing: {relative}')
